apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-cli
    app.kubernetes.io/part-of: build
  name: rhtap-cli
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: rhtap-cli
status:
  loadBalancer: {}
