apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: anewcomponent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: anewcomponent
    app.kubernetes.io/part-of: build
  name: anewcomponent
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: anewcomponent
status:
  loadBalancer: {}
